### ISSUE TITLE
实验结果

### ISSUE THREAD

**Issue by springandsugar2022** [xy-xiaotudou/EmoPrompt-ECPE#2]
作者你好 想问下你的微调参数有更加详细的嘛 我复现出来的结果差了7个点左右 想知道是不是参数原因还是其他什么原因 谢谢作者了

**Comment by zgzis** [comment]
请问你复现出效果了么

**Comment by ewgfsd** [comment]
> 作者你好 想问下你的微调参数有更加详细的嘛 我复现出来的结果差了7个点左右 想知道是不是参数原因还是其他什么原因 谢谢作者了

请问你复现出效果了么？

**Comment by ewgfsd** [comment]
> 作者你好 想问下你的微调参数有更加详细的嘛 我复现出来的结果差了7个点左右 想知道是不是参数原因还是其他什么原因 谢谢作者了

希望得到你的回答，谢谢

**Comment by springandsugar2022** [comment]
已复现出~ 谢谢解答~



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月12日(周四) 中午11:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [xy-xiaotudou/EmoPrompt-ECPE] 实验结果 (Issue #2)




  
作者你好 想问下你的微调参数有更加详细的嘛 我复现出来的结果差了7个点左右 想知道是不是参数原因还是其他什么原因 谢谢作者了
  
请问你复现出效果了么？
